services:
  api-server:
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

  scheduler:
    environment:
      AIRFLOW__CORE__DAG_DIR_LIST_INTERVAL: 30
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 30
      AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: 5